FROM python:3

WORKDIR /usr/src/app

COPY ./setup_files/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./neuroboun/
WORKDIR /usr/src/app/neuroboun

RUN rm ./neuroboun/settings.py &&\
    mv ./setup_files/settings_base__copy_to_neuroboun.py ./neuroboun/settings.py 


CMD sleep 20s &&\

    python manage.py makemigrations &&\
    python manage.py migrate &&\
   
    cp ./setup_files/BrainRegions.csv ./ &&\
    cp ./setup_files/csv_importer.py ./ &&\
    python csv_importer.py &&\
    rm ./BrainRegions.csv &&\
    rm ./csv_importer.py &&\

    cp ./setup_files/pubmed_retrieve_and_save.py ./ &&\
    python pubmed_retrieve_and_save.py &&\
    rm pubmed_retrieve_and_save.py &&\

    python manage.py runserver
